// GS1 Standard Brick Library
// Source: GS1 Global Data Dictionary — E-marked (Essential) attributes per
// GPC brick, derived from the Dillard's Footwear.csv, Clothing.csv, and
// Accessories.csv specification sheets.
// Each Gs1Brick has a code, human-readable name, the segment (CSV file origin),
// and the full list of E-marked extended attributes defined for that brick.

export interface Gs1ExtendedAttribute {
  name: string  // Human-readable attribute name
  code: string  // GS1 attribute code
}

export interface Gs1Brick {
  brickCode: string
  brickName: string
  segment: string
  extendedAttributes: Gs1ExtendedAttribute[]
}

export const GS1_BRICKS: Gs1Brick[] = [
  // ── Footwear ──────────────────────────────────────────────────────────────
  // Brick 10001077 = "Shoes - General Purpose" per Footwear.csv column B.
  {
    brickCode: "10001077",
    brickName: "Shoes - General Purpose",
    segment: "Footwear",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Faux Fur", code: "GM03FXFR" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Heel Height", code: "GM03HLHT" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Open/Closed Toe", code: "GM03OPCT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Shoe Type", code: "GM03SHTP" },
      { name: "Sole Type", code: "GM03SLTP" },
      { name: "Toe Shape", code: "GM03TOES" },
      { name: "Toe Style", code: "GM03TOST" },
    ],
  },
  // Brick 10001070 = "Athletic Footwear - General Purpose" per Footwear.csv column D.
  {
    brickCode: "10001070",
    brickName: "Athletic Footwear - General Purpose",
    segment: "Footwear",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Heel Height", code: "GM03HLHT" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Shoe Type", code: "GM03SHTP" },
      { name: "Sole Type", code: "GM03SLTP" },
      { name: "Sport", code: "SPACTIVITY" },
    ],
  },

  // ── Clothing ──────────────────────────────────────────────────────────────
  // Attributes sourced from Clothing.csv — E-marked columns only, per brick.

  {
    brickCode: "10001333",
    brickName: "Dresses",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Collar Type", code: "GM03CLTP" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Dress Type", code: "GM03DRTP" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gauge", code: "GM03GAUG" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
      { name: "Wrinkle Resistant", code: "GM03WKRS" },
    ],
  },
  {
    brickCode: "10001350",
    brickName: "Jackets/Blazers/Cardigans/Waistcoats",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Coat/Jacket Type", code: "GM03CJTP" },
      { name: "Collar Type", code: "GM03CLTP" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gauge", code: "GM03GAUG" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Hooded", code: "GM03HOOD" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
      { name: "Water Repellent", code: "GM03WTRP" },
      { name: "Wrinkle Resistant", code: "GM03WKRS" },
    ],
  },
  {
    brickCode: "10001352",
    brickName: "Shirts/Blouses/Polo Shirts/T-Shirts",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Collar Type", code: "GM03CLTP" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Hooded", code: "GM03HOOD" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
      { name: "Wrinkle Resistant", code: "GM03WKRS" },
    ],
  },
  {
    brickCode: "10001351",
    brickName: "Sweaters/Pullovers",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Collar Type", code: "GM03CLTP" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gauge", code: "GM03GAUG" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Hooded", code: "GM03HOOD" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
      { name: "Sweater/Pullover Type", code: "GM03SWTP" },
    ],
  },
  {
    brickCode: "10001361",
    brickName: "Upper Body Wear/Tops Variety Packs",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Collar Type", code: "GM03CLTP" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Consumer Quantity of Units in Consumer Package", code: "GM03CQUP" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
    ],
  },
  {
    brickCode: "10001332",
    brickName: "Overalls/Bodysuits",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Collar Type", code: "GM03CLTP" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Leg Type", code: "GM03LGTP" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
    ],
  },
  {
    brickCode: "10001356",
    brickName: "Lower Body Wear/Bottoms Variety Packs",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Consumer Quantity of Units in Consumer Package", code: "GM03CQUP" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Leg Type", code: "GM03LGTP" },
      { name: "Pant Inseam Length", code: "GM03PNIL" },
      { name: "Pants/Shorts Type", code: "GM03PSTP" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Waist Rise", code: "GM03WAIS" },
      { name: "Waistband Type", code: "GM03WBTP" },
    ],
  },
  {
    brickCode: "10001334",
    brickName: "Skirts",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Skirt Type", code: "GM03SKTP" },
      { name: "Waistband Type", code: "GM03WBTP" },
      { name: "Wrinkle Resistant", code: "GM03WKRS" },
    ],
  },
  {
    brickCode: "10001335",
    brickName: "Trousers/Shorts",
    segment: "Clothing",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Leg Type", code: "GM03LGTP" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Pant Inseam Length", code: "GM03PNIL" },
      { name: "Pants/Shorts Type", code: "GM03PSTP" },
      { name: "Pocket Details", code: "GM03PKDT" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Waist Rise", code: "GM03WAIS" },
      { name: "Waistband Type", code: "GM03WBTP" },
      { name: "Wrinkle Resistant", code: "GM03WKRS" },
    ],
  },

  // ── Jewellery ─────────────────────────────────────────────────────────────
  // No dedicated Jewellery CSV supplied — these remain from the GS1 GDD.
  {
    brickCode: "10006017",
    brickName: "Necklaces/Chains/Pendants",
    segment: "Jewellery",
    extendedAttributes: [
      { name: "Metal Type", code: "GM03MTLT" },
      { name: "Metal Purity", code: "GM03MTPU" },
      { name: "Stone Type", code: "GM03STTP" },
      { name: "Chain Length", code: "GM03CHLN" },
      { name: "Closure Type", code: "GM03CLTP" },
      { name: "Gender", code: "GENDER" },
    ],
  },
  {
    brickCode: "10006018",
    brickName: "Rings",
    segment: "Jewellery",
    extendedAttributes: [
      { name: "Metal Type", code: "GM03MTLT" },
      { name: "Metal Purity", code: "GM03MTPU" },
      { name: "Stone Type", code: "GM03STTP" },
      { name: "Stone Cut", code: "GM03STCT" },
      { name: "Ring Size System", code: "GM03RGSZ" },
      { name: "Gender", code: "GENDER" },
    ],
  },
  {
    brickCode: "10006019",
    brickName: "Earrings/Ear Cuffs",
    segment: "Jewellery",
    extendedAttributes: [
      { name: "Metal Type", code: "GM03MTLT" },
      { name: "Metal Purity", code: "GM03MTPU" },
      { name: "Stone Type", code: "GM03STTP" },
      { name: "Earring Fastening", code: "GM03ERFT" },
      { name: "Gender", code: "GENDER" },
    ],
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  // Attributes sourced from Accessories.csv — E-marked columns only, per brick.

  {
    brickCode: "10006030",
    brickName: "Handbags/Purses",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Convertible", code: "GM03CNVT" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Prop 65", code: "GM03PR65" },
    ],
  },
  {
    brickCode: "10001328",
    brickName: "Handwear/Gloves",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Convertible", code: "GM03CNVT" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Glove Type", code: "GM03GLTP" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Prop 65", code: "GM03PR65" },
    ],
  },
  {
    brickCode: "10001329",
    brickName: "Headwear",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Adjustable", code: "GM03ADJB" },
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Hat Type", code: "GM03HATP" },
      { name: "Prop 65", code: "GM03PR65" },
    ],
  },
  {
    brickCode: "10001327",
    brickName: "Pocket Squares/Handkerchiefs",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Item Width", code: "GM03CITW" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Prop 65", code: "GM03PR65" },
    ],
  },
  {
    brickCode: "10001330",
    brickName: "Scarves/Ties/Neckwear",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Item Width", code: "GM03CITW" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Neckwear Type", code: "GM03NWTP" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Scarf Type", code: "GM03SCTP" },
    ],
  },
  {
    brickCode: "10001326",
    brickName: "Belts/Braces/Cummerbunds",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Adjustable", code: "GM03ADJB" },
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Belt Type", code: "GM03BLTP" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Item Width", code: "GM03CITW" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Reversible", code: "GM03RVRS" },
      { name: "Stretch", code: "GM03STRH" },
    ],
  },
  {
    brickCode: "10006032",
    brickName: "Scarves/Wraps/Shawls",
    segment: "Accessories",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Consumer Item Length", code: "GM03CITL" },
      { name: "Consumer Item Width", code: "GM03CITW" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Fur Animal Name", code: "GM03FRAN" },
      { name: "Fur Country of Origin", code: "GM03FRCO" },
      { name: "Fur Treatment", code: "GM03FTMT" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Prop 65", code: "GM03PR65" },
    ],
  },

  // ── Sportswear ────────────────────────────────────────────────────────────
  // No dedicated Sportswear CSV supplied — derived from GS1 GDD plus
  // alignment with Clothing CSV conventions.
  {
    brickCode: "10001400",
    brickName: "Sports/Performance Tops",
    segment: "Sportswear",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Compression Level", code: "GM03CMPL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Hooded", code: "GM03HOOD" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Neckline", code: "GM03NKLN" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
      { name: "Sport/Activity", code: "SPACTIVITY" },
    ],
  },
  {
    brickCode: "10001401",
    brickName: "Sports/Performance Bottoms",
    segment: "Sportswear",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Compression Level", code: "GM03CMPL" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Pant Inseam Length", code: "GM03PNIL" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Rise", code: "GM03RISE" },
      { name: "Sport/Activity", code: "SPACTIVITY" },
    ],
  },

  // ── Homewear ──────────────────────────────────────────────────────────────
  // No dedicated Homewear CSV supplied — derived from GS1 GDD plus
  // alignment with Clothing CSV conventions.
  {
    brickCode: "10002100",
    brickName: "Nightwear/Pyjamas",
    segment: "Homewear",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Prop 65", code: "GM03PR65" },
      { name: "Sleeve Type", code: "GM03SLTP" },
    ],
  },
  {
    brickCode: "10002101",
    brickName: "Robes/Dressing Gowns",
    segment: "Homewear",
    extendedAttributes: [
      { name: "Advertised Origin", code: "GM03ADVOR" },
      { name: "Brand Name", code: "GM03BRNM" },
      { name: "Care Instructions Code", code: "GM03CRIC" },
      { name: "Closure", code: "GM03CLOS" },
      { name: "Consumer Life Stage", code: "CONLIFESTAGE" },
      { name: "Country of Origin", code: "GM03COOR" },
      { name: "Fabric or Material Code", code: "GM03FBMC" },
      { name: "Features - Benefits Marketing Message", code: "GM03FBMM" },
      { name: "Fiber", code: "GM03FIBR" },
      { name: "Gender", code: "GENDER" },
      { name: "Global Product Classification (GPC)", code: "GPC" },
      { name: "Harmonized Tariff Schedule Code", code: "GM03HTSC" },
      { name: "Length Description", code: "GM03LNDS" },
      { name: "Lined", code: "GM03LIND" },
      { name: "Lining Material", code: "GM03LIMT" },
      { name: "Prop 65", code: "GM03PR65" },
    ],
  },
]

/** Look up a brick by its code. Returns undefined if not found. */
export function getBrickByCode(code: string): Gs1Brick | undefined {
  return GS1_BRICKS.find((b) => b.brickCode === code)
}

/** Get all unique segments present in the library. */
export function getSegments(): string[] {
  return [...new Set(GS1_BRICKS.map((b) => b.segment))].sort()
}

/** Search bricks by name, code, or segment (case-insensitive). */
export function searchBricks(query: string): Gs1Brick[] {
  const q = query.toLowerCase().trim()
  if (!q) return GS1_BRICKS
  return GS1_BRICKS.filter(
    (b) =>
      b.brickName.toLowerCase().includes(q) ||
      b.brickCode.includes(q) ||
      b.segment.toLowerCase().includes(q)
  )
}
